- hosts: all
  gather_facts: false

  tasks:
    - name: Install Python
      raw: "apt-get -y -q install python"
      become: true
      retries: 10
      delay: 20
      # NOTE!!!!!If you run this playbook after Terraform allpy, ssh might be not ready  yet


- hosts: etcd
  roles:
    - common
    - etcd

- hosts: controller
  roles:
    - common
    - controller

- hosts: worker
  roles:
    - common
    - worker