- hosts: localhost
  connection: local

  tasks:

  - name: Launch 1 ngix pods
    command: "kubectl run nginx --image=nginx --port=80 --replicas=1"

  - name: Expose nginx
    command: "kubectl expose deployment nginx --type NodePort"

  - name: Get exposed port
    command: "kubectl get svc nginx --output=jsonpath='{range .spec.ports[0]}{.nodePort}'"
    register: result
  - set_fact:
      node_port: "{{ result.stdout }}"

  - debug: msg="Exposed port {{ node_port }}"